import { Project } from "./types";

export const projectsData: Project[] = [
  {
    name: "Youth Leadership Summit",
    barangay: "Bauan",
    chair: "J. Reyes",
    date: "Mar 2024",
    budget: "₱85,000",
    category: "Youth Development",
    status: "done",
  },
  {
    name: "SK Basketball League",
    barangay: "San Jose",
    chair: "M. Santos",
    date: "Feb 2024",
    budget: "₱60,000",
    category: "Sports & Recreation",
    status: "ongoing",
  },
  {
    name: "Free Medical & Dental Mission",
    barangay: "Sorosoro Karsada",
    chair: "A. Cruz",
    date: "Jan 2024",
    budget: "₱45,000",
    category: "Health",
    status: "ongoing",
  },
  {
    name: "Anti-Drug Campaign Seminar",
    barangay: "Alangilan",
    chair: "C. Garcia",
    date: "Dec 2023",
    budget: "₱30,000",
    category: "Peace & Order",
    status: "done",
  },
  {
    name: "Tree Planting & Clean-Up Drive",
    barangay: "Cuta",
    chair: "L. Torres",
    date: "Dec 2023",
    budget: "₱25,000",
    category: "Environment",
    status: "done",
  },
  {
    name: "Nutrition & Health Awareness",
    barangay: "Lemery",
    chair: "F. Ramos",
    date: "Oct 2023",
    budget: "₱35,000",
    category: "Health",
    status: "done",
  },
  {
    name: "Kabataan Film Festival",
    barangay: "San Pascual",
    chair: "G. Lim",
    date: "Oct 2023",
    budget: "₱55,000",
    category: "Arts & Culture",
    status: "pending",
  },
  {
    name: "Youth Entrepreneurship Forum",
    barangay: "As-is",
    chair: "J. Reyes",
    date: "Sep 2023",
    budget: "₱68,000",
    category: "Livelihood",
    status: "ongoing",
  },
  {
    name: "Sports Equipment Procurement",
    barangay: "Cupang",
    chair: "M. Santos",
    date: "Aug 2023",
    budget: "₱50,000",
    category: "Sports & Recreation",
    status: "pending",
  },
];

export const chartColors = [
  "#003366",
  "#FFCC00",
  "#10B981",
  "#3B82F6",
  "#F59E0B",
  "#6366F1",
  "#EC4899",
];
